---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ca-cluster
  region: us-east-1
  version: "1.22"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: nodegroupA
  desiredCapacity: 1
  availabilityZones: ["us-east-1a"]
  instanceType: t3.small
  spot: true
- name: nodegroupB
  desiredCapacity: 1
  availabilityZones: ["us-east-1b"]
  instanceType: t3.small
  spot: true
- name: nodegroupC
  desiredCapacity: 1
  availabilityZones: ["us-east-1c"]
  instanceType: t3.small
  spot: true
